#!/usr/bin/perl

# Removes comments from a LaTeX file.
#
# Copied from https://tex.stackexchange.com/a/83809 ,
# with modifications suggested by commenters there.
# Further modified to kill any material after \end{document}.

# TODO: Handle other kinds of commented-out material such as \iffalse ... \fi.
#       Possibly using latexpand.
#
# TODO: This code only works if the verbatim, comment, and document environments
#       are left-aligned, and if such an environment begins and ends in the same
#       file.
#
# TODO: Improve the Perl style.

use strict 'vars';
&MAIN(@ARGV);
sub MAIN {
   my ($filehandle) = @_;

   open FILE, "<$filehandle";
   my @doc = <FILE>;
   close FILE;

   &removeComments(\@doc);

   foreach my $line ( @doc ){
      print $line;
    }

   return 1;
}

sub removeComments {
   my ($docarray) = @_;

   my $isCommentEnvironment  = "no";
   my $isVerbatimEnvironment = "no";

   my @newdoc;

   foreach my $line ( @{$docarray} ){
      $isVerbatimEnvironment = "yes" if ( $line =~ /^\\begin\{verbatim\}/ );
      $isCommentEnvironment  = "yes" if ( $line =~ /^\\begin\{comment\}/ );
      if ( ($isVerbatimEnvironment eq "no") && ($isCommentEnvironment eq "no") ) {
	 next if ($line =~ /^\s*%/);
	 ## Temporarily replace "%" that you want to keep with a dummy string
	 ## that does not appear elsewhere in your document.  Then, remove remainder
	 ## of lines that still contain "%".
	 if ( $line =~ /\\%/){
	    $line =~ s/\\%/TMP::PERCENT/g;
	    $line =~ s/%.*//;
	    $line =~ s/TMP::PERCENT/\\%/g;
	 } else {
	 ## if the "%" is not preceded by whitespace, then it serves to suppress whitespace, so leave it there although deleting the rest of the comment
	    $line =~ s/\s+%.*//;
	    $line =~ s/%.*/%/;
	 }
	 push @newdoc, $line;
      }
      push @newdoc, $line if ( $isVerbatimEnvironment eq "yes" );

      $isVerbatimEnvironment = "no" if ( $line =~ /^\\end\{verbatim\}/ );
      $isCommentEnvironment  = "no" if ( $line =~ /^\\end\{comment\}/ );
      print STDERR "abc" if ( $line =~ /^\\end\{document\}/ );
      last if ( $line =~ /^\\end\{document\}/ );
   }

   @{$docarray} = @newdoc;
   return 1;
}